import { useState, useRef, useEffect, JSX } from 'react';
import { useParams } from 'react-router-dom';
import { Button } from '@/components/ui-kit/button';
import { Bot, User, Copy, ThumbsUp, ThumbsDown, RotateCcw, Check } from 'lucide-react';
import { GptChatInput } from '../../components/gpt-chat-input/gpt-chat-input';

interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
}

export const GptChatPageDetails = () => {
  const { chatId } = useParams();
  const [message, setMessage] = useState('');
  const [messages, setMessages] = useState<Message[]>([]);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const initialMessage = localStorage.getItem(`chat-initial-${chatId}`);
    if (initialMessage) {
      localStorage.removeItem(`chat-initial-${chatId}`);

      const userMessage: Message = {
        id: '1',
        role: 'user',
        content: initialMessage,
        timestamp: new Date(),
      };

      const aiResponse: Message = {
        id: '2',
        role: 'assistant',
        content: `I understand you're asking about: "${initialMessage}"

Let me help you with that. Here's a comprehensive response:

**Key Points:**
1. This is a generated response based on your question
2. In a real application, this would be connected to an AI model
3. The response would be context-aware and helpful

**Example Code:**
\`\`\`javascript
const example = () => {
  console.log('This is a sample code block');
  return 'Success!';
};
\`\`\`

Is there anything specific you'd like me to elaborate on?`,
        timestamp: new Date(Date.now() + 1000),
      };

      const initialMessages = [userMessage, aiResponse];
      setMessages(initialMessages);
      localStorage.setItem(`chat-${chatId}`, JSON.stringify(initialMessages));
      return;
    }

    const storedMessages = localStorage.getItem(`chat-${chatId}`);
    if (storedMessages) {
      setMessages(JSON.parse(storedMessages));
    }
  }, [chatId]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSendMessage = () => {
    if (!message.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: message,
      timestamp: new Date(),
    };

    const aiResponse: Message = {
      id: (Date.now() + 1).toString(),
      role: 'assistant',
      content: `This is a sample AI response to: "${message}". In a real application, this would be generated by an AI model based on the user's input and conversation context.`,
      timestamp: new Date(Date.now() + 1000),
    };

    const updatedMessages = [...messages, userMessage, aiResponse];
    setMessages(updatedMessages);
    localStorage.setItem(`chat-${chatId}`, JSON.stringify(updatedMessages));
    setMessage('');
  };

  const handleCopy = (content: string, messageId: string) => {
    navigator.clipboard.writeText(content);
    setCopiedId(messageId);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const renderMessageContent = (content: string) => {
    const parts: JSX.Element[] = [];
    const lines = content.split('\n');
    let inCodeBlock = false;
    let codeBlockContent: string[] = [];
    let codeLanguage = '';

    lines.forEach((line, index) => {
      if (line.startsWith('```')) {
        if (!inCodeBlock) {
          inCodeBlock = true;
          codeLanguage = line.replace('```', '').trim();
          codeBlockContent = [];
        } else {
          inCodeBlock = false;
          parts.push(
            <div key={`code-${index}`} className="my-4 group/code relative">
              <div className="absolute top-3 right-3 z-10">
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-7 px-2 text-xs bg-background/80 backdrop-blur-sm hover:bg-background opacity-0 group-hover/code:opacity-100 transition-all duration-200"
                  onClick={() => handleCopy(codeBlockContent.join('\n'), `code-${index}`)}
                >
                  {copiedId === `code-${index}` ? (
                    <>
                      <Check className="h-3 w-3 mr-1" />
                      Copied
                    </>
                  ) : (
                    <>
                      <Copy className="h-3 w-3 mr-1" />
                      Copy
                    </>
                  )}
                </Button>
              </div>
              <div className="bg-muted/50 backdrop-blur-sm border border-border/50 rounded-2xl overflow-hidden">
                {codeLanguage && (
                  <div className="px-4 py-2 border-b border-border/50 bg-muted/30 text-xs text-muted-foreground font-medium">
                    {codeLanguage}
                  </div>
                )}
                <pre className="p-4 overflow-x-auto">
                  <code className="text-sm font-mono leading-relaxed">
                    {codeBlockContent.join('\n')}
                  </code>
                </pre>
              </div>
            </div>
          );
          codeBlockContent = [];
        }
      } else if (inCodeBlock) {
        codeBlockContent.push(line);
      } else {
        if (line.trim()) {
          const formattedLine = line.split('**').map((part, i) =>
            i % 2 === 1 ? (
              <strong key={i} className="font-semibold text-foreground">
                {part}
              </strong>
            ) : (
              part
            )
          );

          if (line.trim().startsWith('-')) {
            parts.push(
              <div key={index} className="flex gap-2 my-1.5 ml-4">
                <span className="text-primary mt-1.5">•</span>
                <span className="flex-1 leading-relaxed">{formattedLine}</span>
              </div>
            );
          } else if (/^\d+\./.test(line.trim())) {
            parts.push(
              <div key={index} className="flex gap-2 my-1.5 ml-4">
                <span className="text-primary font-medium min-w-[20px]">
                  {line.trim().match(/^\d+\./)?.[0]}
                </span>
                <span className="flex-1 leading-relaxed">
                  {line
                    .replace(/^\d+\.\s*/, '')
                    .split('**')
                    .map((part, i) =>
                      i % 2 === 1 ? (
                        <strong key={i} className="font-semibold text-foreground">
                          {part}
                        </strong>
                      ) : (
                        part
                      )
                    )}
                </span>
              </div>
            );
          } else {
            parts.push(
              <p key={index} className="my-2 leading-relaxed">
                {formattedLine}
              </p>
            );
          }
        } else {
          parts.push(<div key={index} className="h-2" />);
        }
      }
    });

    return <div className="text-sm text-foreground/90">{parts}</div>;
  };

  return (
    <div className="flex flex-col h-full w-full bg-gradient-to-b from-background to-muted/20">
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-4xl mx-auto px-4 py-8 space-y-6">
          {messages.map((msg) => (
            <div
              key={msg.id}
              className={`flex gap-4 animate-in fade-in slide-in-from-bottom-4 duration-500 ${
                msg.role === 'user' ? 'justify-end' : 'justify-start'
              }`}
            >
              {msg.role === 'assistant' && (
                <div className="flex-shrink-0 w-10 h-10 rounded-2xl bg-gradient-to-br from-primary/20 to-primary/10 border border-primary/20 flex items-center justify-center shadow-sm">
                  <Bot className="h-5 w-5 text-primary" />
                </div>
              )}

              <div className={`group ${msg.role === 'user' ? '' : 'flex-1 max-w-3xl'}`}>
                <div
                  className={`relative ${
                    msg.role === 'user'
                      ? 'bg-primary text-primary-foreground rounded-3xl px-6 py-4 shadow-lg shadow-primary/30 ml-auto max-w-sm border-1 border-primary/20'
                      : 'bg-card/50 backdrop-blur-sm border border-border/50 rounded-3xl px-6 py-5 shadow-sm hover:shadow-md hover:border-border transition-all duration-300'
                  }`}
                >
                  {msg.role === 'user' ? (
                    <p className="text-base leading-relaxed whitespace-pre-wrap font-medium">
                      {msg.content}
                    </p>
                  ) : (
                    renderMessageContent(msg.content)
                  )}
                </div>

                {msg.role === 'assistant' && (
                  <div className="flex items-center gap-1 mt-2 ml-2 opacity-0 group-hover:opacity-100 transition-all duration-200">
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-8 px-2.5 rounded-xl hover:bg-primary/10 hover:text-primary transition-all duration-200"
                      onClick={() => handleCopy(msg.content, msg.id)}
                    >
                      {copiedId === msg.id ? (
                        <>
                          <Check className="h-3.5 w-3.5 mr-1.5" />
                          <span className="text-xs">Copied</span>
                        </>
                      ) : (
                        <>
                          <Copy className="h-3.5 w-3.5 mr-1.5" />
                          <span className="text-xs">Copy</span>
                        </>
                      )}
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8 rounded-xl hover:bg-primary/10 hover:text-primary transition-all duration-200"
                    >
                      <ThumbsUp className="h-3.5 w-3.5" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8 rounded-xl hover:bg-destructive/10 hover:text-destructive transition-all duration-200"
                    >
                      <ThumbsDown className="h-3.5 w-3.5" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8 rounded-xl hover:bg-primary/10 hover:text-primary transition-all duration-200"
                    >
                      <RotateCcw className="h-3.5 w-3.5" />
                    </Button>
                  </div>
                )}

                <div
                  className={`text-xs text-muted-foreground/60 mt-2 ${
                    msg.role === 'user' ? 'text-right mr-2' : 'ml-2'
                  }`}
                >
                  {new Date(msg.timestamp).toLocaleTimeString([], {
                    hour: '2-digit',
                    minute: '2-digit',
                  })}
                </div>
              </div>

              {msg.role === 'user' && (
                <div className="flex-shrink-0 w-10 h-10 rounded-2xl bg-gradient-to-br from-accent to-accent/80 border border-border flex items-center justify-center shadow-sm">
                  <User className="h-5 w-5 text-foreground" />
                </div>
              )}
            </div>
          ))}
          <div ref={messagesEndRef} />
        </div>
      </div>
      {/* Bottom Toolbar */}

      <GptChatInput
        message={message}
        onMessageChange={setMessage}
        onSendMessage={handleSendMessage}
      />
    </div>
  );
};
